_target_: src.models.ehrf_module.EHRFModule

lr: 0.001
weight_decay: 0.0005
# Neuronal-Conv-1d term
with_conv_1d: True
with_distances: False
conv_1d_hidden_layers: 20

# Latent residuals term
with_latent_fcnn: False
latent_hidden_layers: 3
latent_hidden_layer_dim: 500
latent_hidden_dropout: 0.35

# Vascular mean term
with_vascular_mean: False

# Flags:
generate_pred_csv: False
predictor_ckpt_path: null

# These are (currently) added dynamically, based on the dataset metadata:
# x_size: -
# y_size: -
