_target_: src.models.ehrf_module.EHRFModule

lr: 0.001
weight_decay: 0.0005
latent_dim: 1
hidden_layers: 2
hidden_layer_dim: 100
with_vascular_mean: False
hidden_dropout: 0.2

# These are (currently) added dynamically, based on the dataset metadata:
# x_size: -
# y_size: -
