# @package _global_

# *******
# Simplified configuration for simple, non-torch models (to be used as baselines)
# *******

# specify here default training configuration
defaults:
  - _self_
  - logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - log_dir: default.yaml

  # experiment configs allow for version control of specific configurations
  # e.g. best hyperparameters for each combination of model and datamodule
  - experiment: null

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

  # config for hyperparameter optimization
  - hparams_search: null

  # define the project of monitoring
  #  - logger/wandb/project: "baselines"
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog



# --------------- Baseline Model Logic ---------------
logic:
  # name of dataset
  dataeset_name: "2021_02_01_neurovascular_datasets"
  # name of the variation of the data-process that'll be performed
  data_process_variation: "classic"
  # Ratio of test split of dataset
  data_split_ratio: 0.2
  # name of the 'simple model' to run
  model_name: "linear_regression"
# ------------ [END] Baseline Model Logic -------------


# path to original working directory
# hydra hijacks working directory by changing it to the new log directory
# https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
original_work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${original_work_dir}/data/

# pretty print config at the start of the run using Rich library
print_config: True

# disable python warnings if they annoy you
ignore_warnings: True

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# seed for random number generators in pytorch, numpy and python.random
seed: null

# default name for the experiment, determines logging folder path
# (you can overwrite this name in experiment configs)
name: "baseline_default"
