_target_: src.datamodules.neurovascu_datamodule.NVDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [0.85, 0.075, 0.075]  # DO NOT OVERRIDE THIS - As we want the val-set to be the same across experiments.
num_workers: 0
pin_memory: False

# Dataset object with Hyper-parameters

# [Option-1]: NVDataset_Classic
#dataset_object:
#  _target_: src.datamodules.components.nv_datasets.NVDataset_Classic
#  data_dir: ${data_dir} # data_dir is specified in config.yaml
#  dataset_name: 2021_02_01_18_45_51_neurovascular_partial_dataset
#  window_len_neuro_back: 3
#  window_len_neuro_forward: 2
#  window_len_vascu_back: 2
#  window_len_y: 1
#  poly_degree:
#  aggregate_window: "flatten"
#  scaling_method:

# [Option-2]: NVDataset_EHRF
dataset_object:
  _target_: src.datamodules.components.nv_datasets.NVDataset_EHRF
  data_dir: ${data_dir}  # data_dir is specified in config.yaml
  dataset_name: 2021_02_01_18_45_51_neurovascular_partial_dataset
  window_len_neuro_back: 5
  window_len_neuro_forward: 2
  scaling_method: "neuro_normalize"

# [Option-3]: NVDataset_Tabular
#dataset_object:
#  _target_: src.datamodules.components.nv_datasets.NVDataset_Tabular
#  data_dir: ${data_dir}  # data_dir is specified in config.yaml
#  dataset_name: 2021_02_01_18_45_51_neurovascular_partial_dataset
#  include_vascular_idx: True
#  include_vascular_avg: True
#  include_vascular_distances: True
#  window_len_neuro_back: 5
#  window_len_neuro_forward: 3
#  neuro_aggr_method: 'flatten'