_target_: src.datamodules.neurovascu_datamodule.NVDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
datasets_names:
  - 2021_02_01_neurovascular_datasets
  # - TODO ...Add more datasets
batch_size: 64
train_val_test_split: [2000, 500, 400]
num_workers: 0
pin_memory: False

# Data Hyper-parameters
window_len_neuro_back: 5
window_len_neuro_forward: 3
window_len_vascu_back: 2
poly_degree: None
aggregate_window: "flatten"
