_target_: src.datamodules.neurovascu_datamodule.NVDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
datasets_names:
  - 2021_02_01_neurovascular_datasets
  # - TODO ...Add more datasets
batch_size: 64
train_val_test_split: [2000, 950, 1]
num_workers: 0
pin_memory: False

# Dataset object with Hyper-parameters

# [Option-1]: NVDataset_Classic
#dataset_object:
#  _target_: src.datamodules.components.nv_datasets.NVDataset_Classic
#  data_dir: ${data_dir} # data_dir is specified in config.yaml
#  dataset_name: 2021_02_01_neurovascular_datasets
#  window_len_neuro_back: 3
#  window_len_neuro_forward: 2
#  window_len_vascu_back: 2
#  window_len_y: 1
#  poly_degree:
#  aggregate_window: "flatten"
#  scale_method:

# [Option-2]: NVDataset_EHRF
dataset_object:
  _target_: src.datamodules.components.nv_datasets.NVDataset_EHRF
  data_dir: ${data_dir}  # data_dir is specified in config.yaml
  dataset_name: 2021_02_01_neurovascular_datasets
  window_len_neuro_back: 5
  window_len_neuro_forward: 2

